version: 'latest'

services:
  template-devcontainer-python:
    build:
      context: ../
      dockerfile: Dockerfile
      target: development
      tags:
        - template-devcontainer-python:latest
      args:
        USER: user # the user name
        USER_PASSWORD: password # the user password
        USER_SUDO_ENABLED: true # enable sudo for the user
        GROUP_NAME: user # the group name
        UID: 1000
        GID: 1000
        WORKSPACE_DIR: /workspace
        PYTHNON_VERSION: 3.12
        POETRY_HOME: /poetry
    container_name: template-devcontainer-python
    environment:
      ZSH_THEME: agnoster
      POETRY_VIRTUALENVS_IN_PROJECT: true
    volumes:
      - ../:/workspace
